#!/bin/bash

export PYTHONPATH=.

# Run migrations before spinning up the app
alembic --config app/migrations/alembic.ini upgrade head

# Run migration and create initial db
python -m app.db_initializer

# Start up the server
python -m app.start
